[package]
name = "crypto-bigint-asm"
version = "0.1.0"
edition = "2024"

[dependencies]
crypto-bigint = "0.6"
tracing = "0.1"

[dev-dependencies]
test-log = { version = "0.2.17", features = ["trace"] }
